# Generated by Django 5.2.5 on 2026-02-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nonce',
            fields=[
                ('nonce', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Nonce')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='Nonce created at')),
                ('consumed', models.BooleanField(default=False, verbose_name='Consumed')),
            ],
            options={
                'verbose_name': 'Nonce',
                'verbose_name_plural': 'Nonces',
            },
        ),
        migrations.RemoveField(
            model_name='attestedfcmdevice',
            name='attest_nonce',
        ),
        migrations.RemoveField(
            model_name='attestedfcmdevice',
            name='attest_nonce_created_at',
        ),
        migrations.AddField(
            model_name='attestedfcmdevice',
            name='public_key_der',
            field=models.BinaryField(blank=True, null=True, verbose_name='Public key (iOS)'),
        ),
    ]
