# Generated by Django 5.2.5 on 2026-05-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0002_nonce_remove_attestedfcmdevice_attest_nonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestedfcmdevice',
            name='uid',
            field=models.TextField(null=True, verbose_name='User identifier'),
        ),
    ]
